### ISSUE TITLE
new species to be added?

### ISSUE THREAD

**Issue by BCArg** [andrewjpage/krocus#10]
Hi Andrew, 

any plans on adding new species to `krocus_database_downloader -l`? We have several projects with legionella spp. at the hospital where I work and it would be great to have this species added to the DB.

Best regards

**Comment by andrewjpage** [comment]
Hi,
All available MLST schemes on pubmlst.org are available, but I'm afraid the species you mention isnt available, perhaps ask the authors to submit it? Most MLST tools pull in their databases from pubmlst.  I know Sophia David did a comprehensive typing scheme which might prove to be useful https://jcm.asm.org/content/54/8/2135 and she is also working on https://pathogen.watch which supports Legionella analysis in a straightforward web interface.  Perhaps she can advise you?
Regards,
Andrew
