### ISSUE TITLE
Tool output questions

### ISSUE THREAD

**Issue by Karhide** [andrewjpage/krocus#2]
Hi there!

I gave your tool a spin recently (latest version) and just had a few questions, possibly leading to updated documentation.

1. What do the asterisks mean, e.g. gmk(319)* ?
2. Why do I see multiple of the same MLST profiles identified? E.g.:
`Novel	tpi(216)	gmk(319)	yqiL(182)	arcC(46)	glpF(223)	aroE(484)	pta(131)`
`Novel	tpi(216)	gmk(319)	yqiL(182)	arcC(46)	glpF(223)	aroE(484)	pta(131)`

I have a feeling these might be dumb questions, so thanks in advance!

**Comment by andrewjpage** [comment]
Thanks for testing it out.  I'll have to add some documentation!

By default every X number of reads it will print out the current predicted
MLST profile. You can set it to just print everything out at the end after
processing all reads. The idea is that you can stop it running when a
consistent result pops out (e.g. if you are running it in real time while
sequencing on a minION).
The star indicates a partial match.

Andrew

**Comment by Karhide** [comment]
Thanks for the clarification, everything makes sense now, as expected I was being a numpty!
