### ISSUE TITLE
Tool output documentation

### ISSUE THREAD

**Issue by Adoni5** [andrewjpage/krocus#3]
After reading your paper, I was curious to try krocus with some Nanopore long reads. However I was a little confused about the meaning of the output, and was wondering if you could point me in the right direction? 

I assume novel indicates a novel allelic profile, and the numbers correspond to the number of matched reads. I was wondering though, could this be used to identify the presence of a bacterium in a sample?

Many Thanks,
Rory

**Comment by andrewjpage** [comment]
Hi Rory,
In MLST every unique sequence is assigned an identifier. The numbers you see are not the reads, but this identifier. Similar formats are used in other MLST software.  By default the software prints out the best guess of the sequence type every X reads.

You might be able to identify the presence of a bacterium, but it depends on the bacteria and your use-case. For example if you run an E.coli sample through a Klebsiella or Salmonella database, you will get a few genes matching. 
Regards,
Andrew

**Comment by Adoni5** [comment]
Hi Andrew, 
Thank you kindly for your quick response, it has been very helpful!
Cheers,
Rory
