### ISSUE TITLE
Krokus miscall with E coli MLST

### ISSUE THREAD

**Issue by davidgPHE** [andrewjpage/krocus#5]
Hi Andrew,
We had two samples which we sequenced via Nanopore which we know are STEC ST11 (12,12,8,12,15,2,2) using our E. coli MLST database, we used krocus (default parameters) with the same MLST database to sequence type them and originally got both samples coming back as an SLV of ST - ST7806 (12,1068,8,12,15,2,2).

I played around with the parameters a bit such as --kmer 15, --margin 500 and managed to get one of the samples samples as ST11 however, the other is still an SLV of ST11 (ST7806).

Our ONT sequences are on the NCBI SRA under SRR7477813 and SRR7477814 if you wish to access them. 

We were wondering if you could help us? 

Thanks!
David.

**Comment by andrewjpage** [comment]
Hi David,
Great to hear your using the software. I've fixed the underlying issue so it should work out of the box on your data. There was a 9 base repeat in the middle of the gene which caused it to get a bit confused, but its working now (I only tested it on SRR7477813 as I'm on holidays atm). Let me know how you get on.
Andrew

**Comment by fabienneaf** [comment]
Hi Andrew,
So far Krocus was working very good for our bacterial isolates after Oxford-nanopore sequencing. :) We have been running assays for S. aureus and K. pneumoniae sequence reads. However, this week we have run for the first time the database 1 for E. coli. Although our sequencing looks very good (we did the quality control and there is an average of 100X of coverage among the isolates) we did not get results when using Krocus for it. All our 6 E.coli isolates resulted in "ND" ST. When I tried to run the database 2 for E. coli, It ran very good again and I got perfect STs for all the isolates. Is there some issue about the database 1? Any clue? Thank you! Fabienne

**Comment by andrewjpage** [comment]
Hi,
Thanks for the feedback.  In the first instance try downloading the latest
version just in case theres something with the DB.
krocus_database_downloader -o databases/Escherichia_coli_1 -s 'Escherichia
coli#1'
I've run the Escherichia coli#1 DB over a range of nanopored ecoli and the
performance was disappointing.
Using a different method (galru, coming soon) I doubled the number of STs
recovered, however in that dataset there was a wide range of coverage so
its not generalisable.
Andrew

**Comment by fabienneaf** [comment]
Thank you very much, Andrew. I`ll try to download the latest version of the database then.
