### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by karel-brinda** [andrewjpage/krocus#7]
The `conda install` command from `simulations/download_nctc.sh` doesn't work due to a conflict in dependencies:
```
$ conda install -c bioconda pbh5tools krocus mlst

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - krocus
  - pbh5tools
Use "conda info <package>" to see the dependencies for each package.
```

I tested that only on OS X.

**Comment by andrewjpage** [comment]
Hi Karel,
I've pushed a fix. Theres also a container available for pbh5tools:

```
docker pull quay.io/biocontainers/pbh5tools:0.8.0--py27h470a237_1
```
It would be great if the archives made the raw data available in a more common format like FASTQ or BAM.
Andrew

**Comment by karel-brinda** [comment]
Hi Andrew, thanks for the fix.
