### ISSUE TITLE
Support for FASTA files?

### ISSUE THREAD

**Issue by OscarAspelin** [andrewjpage/krocus#8]
Hi, I just have a quick question about file formats. I've tried Krocus with a couple of FASTQ files and it's been working great. Can I use a FASTA file aswell or will this break the software?

**Comment by andrewjpage** [comment]
Hi,
Thanks for the feedback. It currently only supports FASTQ files as input, however it should be straightforward adapt it for FASTA files, so please feel free to submit a pull request with this feature enhancement if you wish.
Regards,
Andrew
